### ISSUE TITLE
GenerateNumbers Test

### ISSUE THREAD

**Issue by normaloide** [ArmeF97/GestoreContattiJava#3]
Per i test usa il unit testing, senza metodi formali il test è affidabile ma non valido

[JUnit](https://junit.org/junit4/javadoc/4.12/org/junit/Assert.html)
[Mockito](https://site.mockito.org/)

**Comment by ArmeF97** [comment]
Ma tu la usi davvero questa repo?

**Comment by normaloide** [comment]
Non io ma a qualcuno potrebbe essere utile
